apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-minio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-minio-app
  template:
    metadata:
      labels:
        app: flask-minio-app
    spec:
      containers:
      - name: flask-minio-app
        image: fdahmen/flask-minio-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret_key
        - name: MINIO_API_HOST
          value: "http://minio-service:9000"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: flask-minio-app

